
services:
  mysql:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"


  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=ap-southeast-2
    ports:
      - "4566:4566"

  app:
    build: .
    depends_on:
      - mysql
      - localstack
      - redis
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=ap-southeast-2

  redis:
    image: redis:7
    ports:
      - "6379:6379"
